services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfinity\UxBlocksLive\:
    resource: '../src/'
    exclude:
      - '../src/SymfinityUxBlocksLiveBundle.php'
      - '../src/DependencyInjection/'

  Symfinity\UxBlocksLive\Controller\CatalogController:
    tags: ['controller.service_arguments']
